config/routes.rb
Rails.application.routes.draw do
    devise_for :users, class_name: "Public::User"
    root to: 'homes#top'
    get 'public/Relationships'
    namespace :public do
    resources :users,only: [:show,:edit,:update,:destroy] do
      get 'followers' => 'relationships#followers', as: 'followers'
      get 'followings' => 'relationships#followings', as: 'followings'
      resource :relationships, only: [:create, :destroy]
    end
    resources :tweets do
      resources :tweet_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/user.rb
class Admin::User < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/public.rb
module Public
  def self.table_name_prefix
    'public_'
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

def after_sign_in_path_for(resource)
    public_user_path(resource)
end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
 def top

 end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcom!</h1>
      <h3>
        ここはあなたという一人の人間のことをみんなに知ってもらう場です。<br>
        節度ある発言を心がけましょう心掛けましょう！
      </h3>
    </div>
  </div>
  <div claas="btn-wrapper col-10 mx-auto">
    <div class="row">
     <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
     <%= link_to "Sing_up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
     <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ルックミー</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div claas="">
　 <sideber>
　  <% if user_signed_in? %>
　 <li><%= link_to "Home", public_user_path(current_user) %></li>
　  <li><%= link_to "tweet", public_tweets_path %></li>
　  <%# link_to "通知" %>
　  <%# link_to "DM" %>
　  <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
　  <% end %>
　 </sideber>
　</div>
    <%= yield %>
  </body>
</html>